name: Playwright Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: saltcorn_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - run: psql -d saltcorn_test --command='create extension "uuid-ossp";'
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGDATABASE: saltcorn_test
          PGPASSWORD: postgres
      - run: npm install --legacy-peer-deps
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
          SKIP_DOCKER_IMAGE_INSTALL: "true"
      - run: npm run tsc
      - name: Install dependencies
        run: npm ci
        working-directory: ./deploy/playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./deploy/playwright
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./deploy/playwright
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: deploy/playwright/playwright-report/
          retention-days: 30
